# Generated by Django 2.2.1 on 2019-05-11 09:48

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_carinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='remark',
            field=DjangoUeditor.models.UEditorField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
