# Generated by Django 2.2.1 on 2019-05-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMdemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInfos',
        ),
    ]
