# Generated by Django 2.2.1 on 2019-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMdemo', '0002_auto_20190512_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
